### ISSUE TITLE
Referrer policy of referencing in SVG?

### ISSUE THREAD

**Issue by tungnh28** [w3c/webappsec-referrer-policy#108]
I am implementing Referrer policy for CSS for FireFox and I can think of SVG resource documents referenced by CSS properties, e.g. filter:url(...)
It seems like the spec is short here
https://w3c.github.io/webappsec-referrer-policy/#integration-with-css seems work to some cases CSS of SVG element inside an HTML page. 
But I think there're cases that we fetch resources in SVG. Should we explain something in the spec, given the complexity of referencing in SVG?
@jeisinger, @estark37 what do you think?

**Comment by annevk** [comment]
If SVG is used as filter it can load further subresources? That seems somewhat problematic.

**Comment by jeisinger** [comment]
SVG doesn't even try to explain how it loads resources, so short of specifying that in the referrer policy spec how SVG works, there's not much we can do :/

**Comment by tungmangtdh3** [comment]
Thanks, how Chrome do with that sorts of referencings if they are allowed?  default value? @jeisinger

**Comment by annevk** [comment]
@tungmangtdh3 from what I remember Chrome and Firefox have a rather divergent story here (SVG resources linked from CSS) and nobody has thus far fixed it.

cc @tabatkins

**Comment by dbaron** [comment]
So I think there's a mixing of two separate issues here:

* SVG resource documents referenced from CSS properties, such as `filter: url(filters.svg#blur2)`, seem like they're already well covered by the [section on Integration with CSS](https://w3c.github.io/webappsec-referrer-policy/#integration-with-css).
* the behavior of a toplevel SVG document referencing images or other SVG documents, or of one SVG resource document referencing images or another SVG resource document ought to be well defined; it seems like the referrer ought to be the linking document, and the policy its policy, but I don't see a definition of this.

What issues make this interesting other than the scope of caching (when, e.g., more than one style sheet or SVG resource document associated with a single toplevel document links to the same resource)?  (Scope, say, in terms of whether the cache is per-toplevel-document or finer grained in terms of resource type or source of link.)

**Comment by dbaron** [comment]
(Oh, and those two issues seem to be covered by [Mozilla bug 1330487](https://bugzilla.mozilla.org/show_bug.cgi?id=1330487) and [Mozilla bug 1415044](https://bugzilla.mozilla.org/show_bug.cgi?id=1415044).)

**Comment by jeisinger** [comment]
thanks for clarifying. Yes, loading SVG resources from CSS is covered by the spec.

**Comment by mikewest** [comment]
@jeisinger: Can we close this?

**Comment by Malvoz** [comment]
The [SVG2 draft](https://svgwg.org/svg2-draft/single-page.html) now both defines the [`referrerpolicy` IDL](https://svgwg.org/svg2-draft/single-page.html#linking-AElementReferrerpolicyAttribute) and [processing modes](https://svgwg.org/svg2-draft/conform.html#processing-modes). Is it too early to specify integration with SVG because it is ED? Perhaps I should read up on W3C process...

**Comment by domfarolino** [comment]
It sounds like this has been blocked on external unclarities around SVG loading in general, and I don't think anything here has changed. We could leave this issue open for another 4~5 years, but since this isn't actionable, I feel like we should close this for now. Feel free to re-open if you think otherwise though.
