### ISSUE TITLE
Should JavaScript module imports respect referrer policy, and if so, how?

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-referrer-policy#111]
In https://github.com/whatwg/html/issues/1150 some folks decided that given

``` html
<!-- x.html -->
<script type="module" src="a.js">
```

``` js
// a.js
import "./b.js";
```

the referrer when fetching `b.js` should be `a.js`, not `x.html`. This apparently follows CSS, which is nice.

However, we didn't think about referrer policies. It seems like if we were to follow CSS [as specified in Referrer Policy](https://w3c.github.io/webappsec-referrer-policy/#integration-with-css), we should be checking for a Referrer-Policy header on a.js, and then falling back to x.html's referrer policy if no such header were present. Does that sound reasonable?

**Comment by mikewest** [comment]
@domenic: Has this been defined in the intervening ~year?

If not, @jeisinger: opinions? :)

**Comment by domfarolino** [comment]
Ah yes yes, thanks for the ping. I should get on this!

**Comment by domenic** [comment]
So the OP has an easy situation: `x.html -> a.js -> b.js`. Here are two harder situations:

### Deeper graph

I.e., `x.html -> a.js -> b.js -> c.js`.

When fetching `c.js`, which referrer policy header do we use? x's (the HTML), a's (the top-level script), or b's (the referrering script)?

a's seems like a strange choice; either x or b seem more consistent to me.

### Multiple referrers

Consider:

```html
<!-- x.html -->
<script type="module" src="a.js">
<script type="module" src="b.js">
```

```js
// a.js
import "./c.js";
```

```js
// b.js
import "./c.js";
```

This will fetch a and b in parallel, and whichever of them finishes being parsed first, will kick off a fetch to c.js.

Which referrer should we use for c.js?

---

In both cases, I wonder what CSS does? (With its `@import` and `background: url()` etc. functionality, which per https://w3c.github.io/webappsec-referrer-policy/#integration-with-css supposedly respect the style sheet's referrer policy.)

**Comment by annevk** [comment]
CSS doesn't do de-duplication of imports as far as I know though perhaps certain caches can make that happen anyway. I doubt that's well-tested also with how many hits a service worker gets, for instance.

If CSS does some de-duplication due to these caches it would be a race.

cc @emilio @noamr

**Comment by emilio** [comment]
CSS definitely coalesces loads of the same `@import uri` (and even the same `<link>` element, as long as it's same-origin actually).

**Comment by annevk** [comment]
You mean that it's defined by the specification? Or that it's a thing implementations do?

**Comment by emilio** [comment]
It's a thing implementations do. I don't think the spec defines it.

**Comment by domfarolino** [comment]
> a's seems like a strange choice; either x or b seem more consistent to me.

I agree. I'll amend https://github.com/whatwg/html/pull/9210 to not be influenced by _isTopLevel_.

>> CSS doesn't do de-duplication of imports
>> If CSS does some de-duplication due to these caches it would be a race.

> CSS definitely coalesces loads of the same `@import uri`

What do we mean by "de-duplication" and "coalescing"? Are we talking about destination-specific mechanisms, like whether the CSS "infra" holds onto some map of finished requests that it can use to serve other similar requests (that might only differ by referrer policy), similar to a module script's "module map"? If so, regardless of some mechanism's explicit existence, this sounds like the memory cache which has [already been acknowledge](https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-module-system:~:text=In%20practice%2C%20due%20to%20the%20as%2Dyet%2Dunspecified%20memory%20cache%20(see%20issue%20%236110)%20the%20resource%20may%20only%20be%20fetched%20once%20in%20WebKit%20and%20Blink%2Dbased%20browsers.) to influence requests like this (depending on whether it keys on referrer policy or not).

I think the question that needs to be answered is: do any de-duplication mechanisms key based on referrer/referrer policy? It doesn't look like Chrome's memory cache does, nor HTML's "module map" (keyed by (URL, module type)), and from @emilio's [comment](https://github.com/w3c/webappsec-referrer-policy/issues/111#issuecomment-1522939248), it sounds like CSS is happy to de-duplicate requests with different referrers/RPs, as long as their same-origin.

Since it seems that we have this behavior all the way down, I'd expect all of these duplicate CSS and module script dependencies to be made with referrers and referrer policies that differ from equivalent resources in the memory cache (or destination-specific mechanism), but to be served by them anyways. It sounds like "which one makes it into the cache first" is acceptably racy, so maybe we don't have to do anything special for this case :) Thoughts?

----

**Aside**:
I suppose another more general question is do we allow the coalescing of _in-flight_ requests (sort of described by [this thread](https://github.com/whatwg/html/issues/7005#issuecomment-914477294)) rather than just the de-duplication of _complete responses_ by a cache? I think this question maybe matters more for general "memory cache" discussion so we can probably ignore it for now.

**Comment by annevk** [comment]
Yeah, it seems like a race is the de facto solution for duplicates in CSS, which seems somewhat acceptable to generalize to module scripts.

**Comment by noamr** [comment]
It seems related to https://github.com/whatwg/fetch/issues/1400.
The specifications are very lacking in the space of defining how in-flight requests and in-memory caching should work.
IMO though, specifically about this, referrerpolicy should never be a cache key, and people who use different referrerpolicies to retrieve the same resource and expect a different result should be aware that this might be racy.

**Comment by noamr** [comment]
> In short, what I mean to say is - shouldn't the policy on the HTML document be enough to ban referrers for good?

Currently the relationship everywhere (e.g. between the document and elements with `referrerpolicy` attributes) is of default->override and not of loose->tighter. @domfarolino might have more context about that but I think that's beyond the scope of decisions specific JS-module imports.
