### ISSUE TITLE
Referrer-Policy header: "strict-same-origin" value

### ISSUE THREAD

**Issue by baptx** [w3c/webappsec-referrer-policy#114]
Hello,

I read that "no-referrer-when-downgrade" is the default value of the Referrer-Policy header, so the Referer header will never be sent if an HTTPS website makes a request to an HTTP website.

If we want to improve the security and privacy, while still having the Referer header on same-origin requests, we could use the "same-origin" value.

But what happens with this value if an HTTPS website makes a same-origin request to an HTTP URL? I guess the Referer header will be sent? So by improving the security with the "same-origin" value, people are also reducing the security on another side.

Is there a "strict-same-origin" value planned, similar to "strict-origin" and "strict-origin-when-cross-origin" values? (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
Otherwise people have to use the "no-referrer" value which will also disable the Referer header on same-origin requests, that is not always what people want and it looks like it is already used as a workaround (https://github.com/rails/rails/issues/28299#issuecomment-335264502).

Thanks.

**Comment by dveditz** [comment]
An origin is defined as "same scheme+host+port". "same-origin" should already do what you want it to do since http://example.com is a different origin than https://example.com -- they are the same host but the scheme and port are different.

it's slightly confusing because a referrer policy "origin" means "send only the origin" and "same-origin" means "send the full Referer, but only TO the same-origin"

If I've misunderstood your request I apologize, and feel free to reopen

**Comment by dveditz** [comment]
An origin is defined as "same scheme+host+port". "same-origin" should already do what you want it to do since http://example.com is a different origin than https://example.com -- they are the same host but the scheme and port are different.

it's slightly confusing because a referrer policy "origin" means "send only the origin" and "same-origin" means "send the full Referer, but only TO the same-origin"

If I've misunderstood your request I apologize, and feel free to reopen

**Comment by baptx** [comment]
Ok, so the "strict-same-origin" effect is already done with the "same-origin" value. And if people want a "same-origin" value that allows sending the Referer header from an HTTPS page to an HTTP page on the same domain, is there a specific value? (I guess people would not need this in most cases)
By the way, will the "same-origin" value send the Referer header from a subdomain to another subdomain on the same domain? Will there be a specific value to allow this?
