### ISSUE TITLE
Clarify priority on five ways of Referrer Policy Delivery

### ISSUE THREAD

**Issue by sulume** [w3c/webappsec-referrer-policy#131]
I do not have much expertise on this area and am not quite sure how this CR is maintained so please advise me if I am on a wrong place for this kind of request.

The section [4. Referrer Policy Delivery](https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery) says:
> A request’s referrer policy is delivered in one of five ways

If I read it correctly, it is not mentioned which value is respected when multiple different values are delivered in more than one way, or multiple values should not be present at once.  There might not be enough hints for readers to realize that confidently. Would it be worth clarifying priority in case of multiple present?

**Comment by domfarolino** [comment]
> If I read it correctly, it is not mentioned which value is respected when multiple different values are delivered in more than one way, or multiple values should not be present at once

I think figuring this out depends on the processing model of a given request. For example a document's referrer policy might be set via a [`<meta>` tag as shown here](https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names:concept-document-referrer-policy). But if a request originates from a `<a>` with a valid `referrerpolicy` attribute, the request's referrer policy will correspond to the value of the attribute, as per [here](https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks:concept-request-referrer-policy). Then later in Fetch, the request's ultimate referrer policy will be [the one provided by the request if given](https://fetch.spec.whatwg.org/#ref-for-concept-request-referrer-policy③), or fall-back to the document's policy otherwise.

So I think the prioritization of delivery is explicit, but buried in the processing model of whatever request you're dealing with. There may be cases of spec ambiguity, but I am not aware of any right now. Does that answer your question?

**Comment by domfarolino** [comment]
@sulume Let me know if there is anything I can clear up, but for now I think I can close this.
