### ISSUE TITLE
"determine request's referrer" algorithm should consult request's referrer policy

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webappsec-referrer-policy#26]
Currently the spec says:

If request was initiated by an element with a referrerpolicy content attribute, let policy be the attribute’s value. Otherwise, let policy be the value of environment’s referrer policy.

That should be something like

If request has a non-empty referrer policy, let policy be that referrer policy. Otherwise, let policy be the value of environment’s referrer policy.

because request's referrer policy can be set via the [Request constructor](https://fetch.spec.whatwg.org/#dom-request).

\<a\> and other elements should set the request referrer policy to its content attribute when fetching (for example, [navigating](https://html.spec.whatwg.org/multipage/browsers.html#navigate)).

**Comment by domenic** [comment]
This is connected to #40 and #43, where the way in which the element's referrer policy gets threaded through to fetch from the various elements is intended to be changed.

**Comment by estark37** [comment]
I think this essence of this issue is fixed now, so I'm going to close it. https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer takes the policy from the request (which Fetch sets from the environment or to the default policy if the request itself doesn't have a policy set). We still need to finish the HTML integration such that elements set the appropriate referrer policy on requests, but I think that's captured by #40 and #43 and doesn't need to be tracked here.

Please let me know if I'm missing something!
