### ISSUE TITLE
Please clarify if header value should be enclosed in quotes or not

### ISSUE THREAD

**Issue by polomsky** [w3c/webappsec-referrer-policy#97]
In point [4.1](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header) is used ABNF, which says that values enclosed in quotation marks are considered as [case insensitive and quotes are ignored](https://tools.ietf.org/html/rfc5234#section-2.3). Other parts of documents suggests that header value should be enclosed in double quotes (headlines are enclosed in quotes except _The empty string_).

Currently it is not clear for me if header value should be in quotes or not because of overused quotes inside other parts of documentation. Same with case sensitivity because of [Enum](https://w3c.github.io/webappsec-referrer-policy/#enumdef-referrerpolicy).

For greater confusion Mozilla uses double quotes in its [reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).

**Comment by estark37** [comment]
The header values shouldn't be quoted.* I think the MDN documentation is wrong. Maybe @Elchi3 can help correct it?

web-platform-tests uses unquoted values, see for example https://github.com/w3c/web-platform-tests/blob/master/referrer-policy/no-referrer-when-downgrade/http-rp/cross-origin/http-http/iframe-tag/insecure-protocol.keep-origin-redirect.http.html.headers

I'm not sure how to make this more clear in the spec; to me it seems that in ABNF a terminal value of `"blah"` is a literal unquoted string, and the Usage example in 4.1.1 makes that explicit. @polomsky do you have any suggestions how to make this more clear?

* Admittedly, we did originally intend for them to be quoted, but forgot to do so in the spec and ended up shipping implementations that were unquoted, so that's what we're stuck with now.

**Comment by Elchi3** [comment]
I corrected the MDN page. Thanks for pinging me! Note that MDN is a wiki, so if you have an account, you can make changes, too :)

**Comment by polomsky** [comment]
Thank you for your quick response and explanation the situation.

My suggestion is to remove quotes from the spec. When is mentioned `Referer` as header name, it is without quotes. When is mentioned [Referrer-Policy](https://w3c.github.io/webappsec-referrer-policy/#parse-referrer-policy-from-header) header, it is without quotes. Only values are quoted everywhere.  Due to this observation I do not see any reason for quoting values. If quotes must be there then they should be at least removed from headlines (3.1, 3.2, ...) and in [section 3](https://w3c.github.io/webappsec-referrer-policy/#referrer-policies) there should be mentioned that values are without quotes. (I saw specs where this is explicitly mentioned).

One of many sources of my confusion was that ABNF uses double quotes and in specs in many places are used double quotes. And I was thinking if this is coincidence or error.

>  to me it seems that in ABNF a terminal value of "blah" is a literal unquoted string

I had to read ABNF RFC again to be sure that quotes are not part of values but still I was unsure.

Thank you again.
